<?php
/**
 * Grouped product data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 * @see Mage_Catalog_Block_Product_View_Type_Grouped
 */
?>
<?php $this->setPreconfiguredValue(); ?>
<?php $_product = $this->getProduct(); ?>
<?php $_associatedProducts = $this->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php echo $this->getChildHtml('product_type_data_extra') ?>
<?php 
$currentLevel = Mage::getModel('eav/entity_attribute')->loadByCode(Mage_Catalog_Model_Product::ENTITY, 'currentlevel'); 
$currentLevelId = $currentLevel->getId();
$currentLeveValues = Mage::getResourceModel('eav/entity_attribute_option_collection')->setPositionOrder('asc')->setAttributeFilter($currentLevelId)->setStoreFilter(0, false)->load()->toOptionArray();

$desiredLevel = Mage::getModel('eav/entity_attribute')->loadByCode(Mage_Catalog_Model_Product::ENTITY, 'desiredlevel'); 
$desiredLevelId = $desiredLevel->getId();
$desiredLeveValues = Mage::getResourceModel('eav/entity_attribute_option_collection')->setPositionOrder('asc')->setAttributeFilter($desiredLevelId)->setStoreFilter(0, false)->load()->toOptionArray();

foreach($_associatedProducts as $_item){
	
}

?>
<div class="block-content-quickorder">
<dl class="leveling">
<dd>
	<select>
    <?php echo "<option>".$currentLevel->getFrontendLabel()."</option>";
		  foreach ($currentLeveValues as $option){echo "<option>".$option["label"]."</option>";}
	?>
  </select>
  <select>
    <?php echo "<option>".$desiredLevel->getFrontendLabel()."</option>";
		  foreach ($desiredLeveValues as $option){echo "<option>".$option["label"]."</option>";}
	?>
  </select>
  <input type="text" value="0" readonly/>
  <input type="text" value="0" readonly/>
  <button type="button" id="product-addtocart-button" class="button btn-cart" onclick="productAddToCartForm.submit(this)">
  		<span><span><?php echo $this->__('Buy') ?></span></span> 
  </button>
  
</dd>
<dl>
</div>

<script>
function loadgrade(){
	alert('asdasd')
}
</script>


<div class="grouped-items-table-wrapper">
  <table class="data-table grouped-items-table" id="super-product-table">
    <col />
    <col />
    <col />
    <tbody>
      <?php if ($_hasAssociatedProducts): ?>
      <?php foreach($_associatedProducts as $_item): ?>
      <?php $_finalPriceInclTax = $this->helper('tax')->getPrice($_item, $_item->getFinalPrice(), true) ?>
      <tr>
        <td class='image'><img class="thumbnail"
                         src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->constrainOnly(true)->resize(105, 80); ?>"
                         alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
                         title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" /></td>
        <td class="name"><p class="name-wrapper"> <?php echo $this->escapeHtml($_item->getName()) ?> </p>
          <?php if ($_product->isSaleable()): ?>
          <div class="qty-wrapper">
            <?php if ($_item->isSaleable()) : ?>
            <input id="super_group_<?php echo $_item->getId(); ?>" type="text" pattern="\d*" name="super_group[<?php echo $_item->getId() ?>]" maxlength="12" value="<?php echo $_item->getQty()*1 ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty" />
            <label for="super_group_<?php echo $_item->getId(); ?>" class="qty-label"> <?php echo $this->__('Quantity'); ?> </label>
            <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
          </div>
          <?php endif; ?></td>
        <?php if ($this->getCanShowProductPrice($_product)): ?>
        <td class="a-right"><?php if ($this->getCanShowProductPrice($_item)): ?>
          <?php echo $this->getPriceHtml($_item, true) ?> <?php echo $this->getTierPriceHtml($_item) ?>
          <?php endif; ?></td>
        <?php endif; ?>
      </tr>
      <?php endforeach; ?>
      <?php else: ?>
      <tr>
        <td colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>"><?php echo $this->__('No options of this product are available.') ?></td>
      </tr>
      <?php endif; ?>
    </tbody>
  </table>
</div>
<script type="text/javascript">decorateTable('super-product-table')</script>
