<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view" id="condition">
  <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
      <?php echo $this->getBlockHtml('formkey') ?>
      <div class="no-display">
        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
      </div>
  <h2 class="subtitle">
    <p><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></p>
  </h2>
      <div class="product-shop">
      	<!-- <div class="product-head">
        <div class="product-name"><span class="h1"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span></div>
        <div class="price-info"><?php echo $this->getPriceHtml($_product); ?> <?php echo $this->getChildHtml('bundle_prices') ?><?php echo $this->getTierPriceHtml() ?></div>
        </div> -->

        <?php echo $this->getChildHtml('alert_urls') ?>
        
        <?php echo $this->getChildHtml('other');?>
        
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
        <?php endif;?>
      </div>
      
      <div class="add-to-cart-wrapper">
      <?php echo $this->getChildHtml('product_type_data') ?>
      <?php echo $this->getChildHtml('extrahint') ?>
      
	  <?php if (!$this->hasOptions()):?>
        <div class="add-to-box">
          <?php if($_product->isSaleable()): ?>
          <?php echo $this->getChildHtml('addtocart') ?>
          <?php endif; ?>
        </div>
      <?php endif; ?>
      
      </div>
      
      <?php if ($_product->getShortDescription()):?>
        <div class="short-description">
          <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
        </div>
        <?php endif;?>

      <?php echo $this->getChildHtml('related_products') ?>
      <div class="clearer"></div>
      <?php if ($_product->isSaleable() && $this->hasOptions()):?>
      <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
      <?php endif;?>
    </form>
    <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
		var str=new String();
  		var arr=new Array();
		str="<?php echo $_product->getShengji(); ?>";
		arr=str.split("||");
		jQuery('.meu_elo_atual').change(function(){
			var currentLevel = parseInt(jQuery(this).get(0).selectedIndex);
			var desiredLevel = parseInt(jQuery('.o_elo_que_mereÇo').get(0).selectedIndex) + 1;
			if(isNaN(desiredLevel) || currentLevel > desiredLevel || currentLevel == desiredLevel){
				jQuery(".o_elo_que_mereÇo").get(0).options[19].selected = true;
				
				var newCurrentLevel = parseInt(jQuery(this).get(0).selectedIndex);
				var newDesiredLevel = parseInt(jQuery('.o_elo_que_mereÇo').get(0).selectedIndex) + 1;
				var find = true; 
				for(var i=0;i<arr.length;i++){
					if(arr[i].indexOf(newCurrentLevel + '-' + newDesiredLevel + '-') > -1 && find){
						var newStr = arr[i].split('-');
						jQuery('.text_time').val(newStr[3]);
						jQuery('.text_price').val(newStr[2]);
						jQuery('#hours').empty();
						jQuery('#money').empty();
						jQuery('#hours').html(newStr[3]);
						jQuery('#money').html(newStr[2]);
						find = false;
					}
				}
			}else{
				
				var newCurrentLevel = parseInt(jQuery(this).get(0).selectedIndex);
				var newDesiredLevel = parseInt(jQuery('.o_elo_que_mereÇo').get(0).selectedIndex) + 1;
				
				var find = true; 
				for(var i=0;i<arr.length;i++){
					if(arr[i].indexOf(newCurrentLevel + '-' + newDesiredLevel + '-') > -1 && find){
						var newStr = arr[i].split('-');
						jQuery('.text_time').val(newStr[3]);
						jQuery('.text_price').val(newStr[2]);
						jQuery('#hours').empty();
						jQuery('#money').empty();
						jQuery('#hours').html(newStr[3]);
						jQuery('#money').html(newStr[2]);
						find = false;
					}
				}
			}
			
			var newCurrentLevel = parseInt(jQuery(this).get(0).selectedIndex);
			var newDesiredLevel = parseInt(jQuery('.o_elo_que_mereÇo').get(0).selectedIndex) + 1;
			if(isNaN(newCurrentLevel) || isNaN(newDesiredLevel)){
				jQuery('.text_time').val('');
				jQuery('.text_price').val('');
			}
		})
		jQuery('.o_elo_que_mereÇo').change(function(){
			var desiredLevel = parseInt(jQuery(this).get(0).selectedIndex) + 1;
			var currentLevel = parseInt(jQuery('.meu_elo_atual').get(0).selectedIndex);

			
			if(currentLevel > desiredLevel || currentLevel == desiredLevel || isNaN(currentLevel)){
				jQuery(".meu_elo_atual").get(0).options[1].selected = true;
				
				var newDesiredLevel = parseInt(jQuery(this).get(0).selectedIndex) + 1;
				var newCurrentLevel= parseInt(jQuery('.meu_elo_atual').get(0).selectedIndex);
				
				var find = true; 
				for(var i=0;i<arr.length;i++){
					if(arr[i].indexOf(newCurrentLevel + '-' + newDesiredLevel + '-') > -1 && find){
						var newStr = arr[i].split('-');
						jQuery('.text_time').val(newStr[3]);
						jQuery('.text_price').val(newStr[2]);
						jQuery('#hours').empty();
						jQuery('#money').empty();
						jQuery('#hours').html(newStr[3]);
						jQuery('#money').html(newStr[2]);
						find = false;
					}
				}
			}else{
				var newDesiredLevel = parseInt(jQuery(this).get(0).selectedIndex) + 1;
				var newCurrentLevel= parseInt(jQuery('.meu_elo_atual').get(0).selectedIndex);
				
				var find = true; 
				for(var i=0;i<arr.length;i++){
					if(arr[i].indexOf(newCurrentLevel + '-' + newDesiredLevel + '-') > -1 && find){
						var newStr = arr[i].split('-');
						jQuery('.text_time').val(newStr[3]);
						jQuery('.text_price').val(newStr[2]);
						jQuery('#hours').empty();
						jQuery('#money').empty();
						jQuery('#hours').html(newStr[3]);
						jQuery('#money').html(newStr[2]);
						find = false;
					}
				}
			}
			var newCurrentLevel = parseInt(jQuery(this).get(0).selectedIndex);
			var newDesiredLevel = parseInt(jQuery('.o_elo_que_mereÇo').get(0).selectedIndex) + 1;
			if(isNaN(newCurrentLevel) || isNaN(newDesiredLevel)){
				jQuery('.text_time').val('');
				jQuery('.text_price').val('');
			}
		})
		jQuery('.text_time').blur(function(){
			var newCurrentLevel = parseInt(jQuery('.meu_elo_atual').get(0).selectedIndex);
			var newDesiredLevel = parseInt(jQuery('.o_elo_que_mereÇo').get(0).selectedIndex) + 1;
			
			var find = true; 
			for(var i=0;i<arr.length;i++){
				if(arr[i].indexOf(newCurrentLevel + '-' + newDesiredLevel + '-') > -1 && find){
					var newStr = arr[i].split('-');
					jQuery('.text_time').val(newStr[3]);
					jQuery('.text_price').val(newStr[2]);
					jQuery('#hours').empty();
					jQuery('#money').empty();
					jQuery('#hours').html(newStr[3]);
					jQuery('#money').html(newStr[2]);
					find = false;
				}
			}
			
		})
		jQuery('.text_price').blur(function(){
			var newCurrentLevel = parseInt(jQuery('.meu_elo_atual').get(0).selectedIndex);
			var newDesiredLevel = parseInt(jQuery('.o_elo_que_mereÇo').get(0).selectedIndex) + 1;
			
			var find = true; 
			for(var i=0;i<arr.length;i++){
				if(arr[i].indexOf(newCurrentLevel + '-' + newDesiredLevel + '-') > -1 && find){
					var newStr = arr[i].split('-');
					jQuery('.text_time').val(newStr[3]);
					jQuery('.text_price').val(newStr[2]);
					jQuery('#hours').empty();
					jQuery('#money').empty();
					jQuery('#hours').html(newStr[3]);
					jQuery('#money').html(newStr[2]);
					find = false;
				}
			}
			
		})

    </script> 
  </div>
  	<!-- Added By Mark 2016/03/11 -->
  	<?php $attributeSetName = Mage::getModel('eav/entity_attribute_set')->load($_product->getAttributeSetId())->getAttributeSetName();?>

  	<?php if ($attributeSetName != 'Default'){ ?>
		
		<div class="after-search">
			<div class="package-button">
				<button class="new_btn"><?php echo $this->__('Nota:')?></button>
			</div>
			<div class="search-result">
				<div class="result-info">
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('search_result')->toHtml() ?>
				</div>
				<!--<div class="buy-field">
					<p>Price:<label class="new-highlight">$<span id ="money">0</span></label>Time:<label class="new-highlight"><span id="hours">0</span> Hours</label></p> <button class="buy-button"><img src="<?php echo $this->getSkinUrl('images/buynow.jpg') ?>"/></button>
				</div> -->
			</div>
		</div>
		<div class="new-welcome-message">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('welcome_to_buy')->toHtml() ?>
		</div>
		
  	<?php } ?>

	
	<!-- Added By Mark 2016/03/11 -->

<?php echo $this->getChildHtml('product_review'); ?>

</div>