<div id="checkout-review" class="onestepcheckout_block">
    <!-- <div class="op_block_title" id="review"><?php echo $this->__('Order Information') ?></div> -->
    <h2 class="subtitle">1.&#160;<?php echo $this->__('Order Information')?></h2>
    <div id="checkout-review-load">
        <?php echo $this->getChildHtml('info') ?>
    </div>
    <div id="checkout-review-submit">    
        <?php echo $this->getChildHtml('agreements') ?>
       
    </div>
</div>